# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 0) do

  create_table "billings", :force => true do |t|
    t.column "created_on",      :timestamp,                                                               :null => false
    t.column "updated_on",      :timestamp,                                                               :null => false
    t.column "number",          :string,    :limit => 20
    t.column "billing_date",    :date
    t.column "person_id",       :integer,                                                :default => 0
    t.column "amount",          :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "outstanding",     :decimal,                 :precision => 10, :scale => 2, :default => 0.0
    t.column "service_billing", :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "expense_billing", :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "days_of_ageing",  :integer
    t.column "business_tax",    :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "status",          :string,    :limit => 1,                                 :default => "0", :null => false
    t.column "collection_days", :integer
    t.column "project_id",      :integer,                                                :default => 0,   :null => false
    t.column "period_id",       :integer,                                                :default => 0,   :null => false
    t.column "write_off",       :integer,   :limit => 10, :precision => 10, :scale => 0,                  :null => false
    t.column "provision",       :integer,   :limit => 10, :precision => 10, :scale => 0,                  :null => false
  end

  add_index "billings", ["project_id", "period_id"], :name => "billing_id"

  create_table "clients", :force => true do |t|
    t.column "chinese_name", :string
    t.column "english_name", :string,                   :default => ""
    t.column "person_id",    :integer,                  :default => 0,  :null => false
    t.column "address_1",    :string
    t.column "person1",      :string,    :limit => 50
    t.column "person2",      :string,    :limit => 50
    t.column "address_2",    :string
    t.column "city_1",       :string
    t.column "city_2",       :string
    t.column "state_1",      :string
    t.column "state_2",      :string
    t.column "country_1",    :string,    :limit => 100
    t.column "country_2",    :string,    :limit => 100
    t.column "postalcode_1", :string,    :limit => 20
    t.column "postalcode_2", :string,    :limit => 20
    t.column "title_1",      :string,    :limit => 50
    t.column "title_2",      :string,    :limit => 50
    t.column "gender1_id",   :integer
    t.column "gender2_id",   :integer
    t.column "mobile_1",     :string,    :limit => 20
    t.column "mobile_2",     :string,    :limit => 20
    t.column "tel_1",        :string,    :limit => 30
    t.column "tel_2",        :string,    :limit => 30
    t.column "fax_1",        :string,    :limit => 20
    t.column "fax_2",        :string,    :limit => 20
    t.column "email_1",      :string
    t.column "email_2",      :string
    t.column "description",  :string
    t.column "category_id",  :integer
    t.column "status_id",    :integer
    t.column "region_id",    :integer
    t.column "industry_id",  :integer
    t.column "client_code",  :string,    :limit => 10,  :default => "", :null => false
    t.column "person3",      :string,    :limit => 50,  :default => "", :null => false
    t.column "title_3",      :string,    :limit => 50,  :default => "", :null => false
    t.column "gender3_id",   :integer,                  :default => 0,  :null => false
    t.column "mobile_3",     :string,    :limit => 20,  :default => "", :null => false
    t.column "tel_3",        :string,    :limit => 20,  :default => "", :null => false
    t.column "fax_3",        :string,    :limit => 20,  :default => "", :null => false
    t.column "email_3",      :string,    :limit => 50,  :default => "", :null => false
    t.column "created_on",   :timestamp,                                :null => false
    t.column "updated_on",   :timestamp,                                :null => false
  end

  add_index "clients", ["person_id", "gender1_id", "gender2_id", "category_id", "status_id", "region_id", "industry_id", "gender3_id"], :name => "client_id"
  add_index "clients", ["client_code"], :name => "client_code"

  create_table "commissions", :force => true do |t|
    t.column "created_on", :timestamp,                                                               :null => false
    t.column "updated_on", :timestamp,                                                               :null => false
    t.column "number",     :string,    :limit => 20
    t.column "date",       :date
    t.column "person_id",  :integer,                                                :default => 0
    t.column "amount",     :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "project_id", :integer,                                                :default => 0,   :null => false
    t.column "period_id",  :integer,                                                :default => 0,   :null => false
  end

  create_table "common_fees", :force => true do |t|
    t.column "period_id",  :integer,  :limit => 10,                                :null => false
    t.column "person_id",  :integer,                                               :null => false
    t.column "common_fee", :integer,  :limit => 10, :precision => 10, :scale => 0, :null => false
    t.column "created_on", :datetime,                                              :null => false
    t.column "updated_on", :datetime,                                              :null => false
  end

  add_index "common_fees", ["period_id", "person_id"], :name => "common_fees_index1297"

  create_table "contacts", :force => true do |t|
    t.column "client_id", :integer,                :default => 0,  :null => false
    t.column "name",      :string,  :limit => 50,  :default => "", :null => false
    t.column "title",     :string,  :limit => 50,  :default => "", :null => false
    t.column "gender",    :integer,                :default => 0,  :null => false
    t.column "mobile",    :string,  :limit => 20,  :default => "", :null => false
    t.column "tel",       :string,  :limit => 20,  :default => "", :null => false
    t.column "fax",       :string,  :limit => 20,  :default => "", :null => false
    t.column "email",     :string,  :limit => 50,  :default => "", :null => false
    t.column "other",     :string,  :limit => 250, :default => "", :null => false
  end

  create_table "costs", :force => true do |t|
    t.column "amount",         :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "item_id",        :integer,                                                  :null => false
    t.column "project_id",     :integer,                                                  :null => false
    t.column "department_id",  :integer,                                                  :null => false
    t.column "cost_status_id", :integer,                                                  :null => false
    t.column "description",    :string,                                  :default => "",  :null => false
    t.column "created_on",     :datetime,                                                 :null => false
    t.column "updated_on",     :datetime,                                                 :null => false
  end

  create_table "deductions", :force => true do |t|
    t.column "created_on",      :timestamp,                                                 :null => false
    t.column "updated_on",      :timestamp,                                                 :null => false
    t.column "service_PFA",     :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "service_UFA",     :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "service_billing", :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "expense_PFA",     :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "expense_UFA",     :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "expense_billing", :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "project_id",      :integer,                                  :default => 0,   :null => false
  end

  create_table "dicts", :force => true do |t|
    t.column "category", :string, :limit => 50
    t.column "code",     :string, :limit => 50
    t.column "title",    :string
  end

  add_index "dicts", ["code"], :name => "code"

  create_table "expenses", :force => true do |t|
    t.column "created_on",         :timestamp,                                                 :null => false
    t.column "updated_on",         :timestamp,                                                 :null => false
    t.column "commission",         :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "outsourcing",        :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "tickets",            :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "courrier",           :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "postage",            :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "stationery",         :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "report_binding",     :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "cash_advance",       :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "period_id",          :integer,                                  :default => 0,   :null => false
    t.column "project_id",         :integer,                                  :default => 0,   :null => false
    t.column "payment_on_be_half", :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "memo",               :string
  end

  add_index "expenses", ["period_id", "project_id"], :name => "expense_id"

  create_table "incomes", :force => true do |t|
    t.column "item_id",        :integer,                                                  :null => false
    t.column "project_id",     :integer,                                                  :null => false
    t.column "department_id",  :integer,                                                  :null => false
    t.column "amount",         :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "cost_status_id", :integer,                                                  :null => false
    t.column "description",    :string,                                  :default => "",  :null => false
    t.column "created_on",     :datetime,                                                 :null => false
    t.column "updated_on",     :datetime,                                                 :null => false
  end

  create_table "industries", :force => true do |t|
    t.column "code",  :string, :limit => 50, :default => "", :null => false
    t.column "title", :string,               :default => "", :null => false
  end

  create_table "initialfees", :force => true do |t|
    t.column "created_on",         :datetime
    t.column "updated_on",         :datetime
    t.column "service_fee",        :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "commission",         :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "outsourcing",        :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "reimbursement",      :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "meal_allowance",     :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "travel_allowance",   :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "business_tax",       :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "tickets",            :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "courrier",           :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "postage",            :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "stationery",         :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "report_binding",     :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "payment_on_be_half", :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "project_id",         :integer,                                 :default => 0,   :null => false
    t.column "cash_advance",       :decimal,  :precision => 10, :scale => 2, :default => 0.0, :null => false
  end

  create_table "items", :force => true do |t|
    t.column "code",      :string, :limit => 2,  :default => "", :null => false
    t.column "titlename", :string, :limit => 50, :default => "", :null => false
    t.column "img_url",   :string,               :default => "", :null => false
  end

  create_table "limit_fees", :force => true do |t|
    t.column "period_id",  :integer,  :limit => 10,                                                :null => false
    t.column "person_id",  :integer,                                                               :null => false
    t.column "limit_fee",  :integer,  :limit => 10, :precision => 10, :scale => 0,                 :null => false
    t.column "created_on", :datetime,                                                              :null => false
    t.column "updated_on", :datetime,                                                              :null => false
    t.column "remark",     :string,                                                :default => "", :null => false
  end

  add_index "limit_fees", ["period_id", "person_id"], :name => "limit_fees_index1301"

  create_table "outsourcings", :force => true do |t|
    t.column "created_on", :timestamp,                                                             :null => false
    t.column "updated_on", :timestamp,                                                             :null => false
    t.column "number",     :string,    :limit => 20
    t.column "date",       :date
    t.column "person_id",  :integer,                                                :default => 0
    t.column "amount",     :decimal,                 :precision => 10, :scale => 2
    t.column "project_id", :integer,                                                :default => 0, :null => false
    t.column "period_id",  :integer,                                                :default => 0, :null => false
  end

  create_table "overtimes", :force => true do |t|
    t.column "created_on", :timestamp,                                                 :null => false
    t.column "updated_on", :timestamp,                                                 :null => false
    t.column "person_id",  :integer
    t.column "ot_date",    :date
    t.column "real_hours", :decimal,   :precision => 10, :scale => 2, :default => 0.0
    t.column "ot_hours",   :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "ot_type_id", :integer
  end

  create_table "people", :force => true do |t|
    t.column "created_on",        :timestamp,                                                               :null => false
    t.column "updated_on",        :timestamp,                                                               :null => false
    t.column "chinese_name",      :string,    :limit => 50,                                :default => ""
    t.column "english_name",      :string,    :limit => 50,                                :default => ""
    t.column "employee_number",   :string,    :limit => 10
    t.column "department_id",     :integer
    t.column "grade",             :string,    :limit => 50
    t.column "charge_rate",       :decimal,                 :precision => 10, :scale => 2, :default => 0.0
    t.column "employeement_date", :date
    t.column "address",           :string
    t.column "postalcode",        :string,    :limit => 10
    t.column "mobile",            :string,    :limit => 20
    t.column "tel",               :string,    :limit => 20
    t.column "extension",         :string,    :limit => 10
    t.column "gender_id",         :integer
    t.column "status_id",         :integer
    t.column "GMU_id",            :integer,                                                :default => 0
  end

  add_index "people", ["department_id", "gender_id", "status_id", "GMU_id"], :name => "person_id"

  create_table "periods", :force => true do |t|
    t.column "number",        :string,   :limit => 50, :default => "0", :null => false
    t.column "starting_date", :date,                                    :null => false
    t.column "ending_date",   :date,                                    :null => false
    t.column "created_on",    :datetime,                                :null => false
  end

  create_table "personalcharges", :force => true do |t|
    t.column "created_on",       :timestamp,                                                 :null => false
    t.column "updated_on",       :timestamp,                                                 :null => false
    t.column "hours",            :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "service_fee",      :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "reimbursement",    :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "meal_allowance",   :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "travel_allowance", :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "project_id",       :integer,                                  :default => 0,   :null => false
    t.column "period_id",        :integer,                                  :default => 0,   :null => false
    t.column "person_id",        :integer,                                  :default => 0,   :null => false
  end

  add_index "personalcharges", ["project_id", "period_id", "person_id"], :name => "personalchg_id"

  create_table "prj_expense_logs", :force => true do |t|
    t.column "prj_id",     :integer
    t.column "expense_id", :integer
    t.column "period_id",  :integer
    t.column "other",      :string,  :default => "", :null => false
  end

  create_table "projects", :force => true do |t|
    t.column "created_on",             :timestamp,                                                               :null => false
    t.column "updated_on",             :timestamp,                                                               :null => false
    t.column "contract_number",        :string,    :limit => 50,                                :default => "",  :null => false
    t.column "client_id",              :integer,                                                :default => 0,   :null => false
    t.column "GMU_id",                 :integer,                                                :default => 0,   :null => false
    t.column "service_id",             :integer,                                                :default => 0,   :null => false
    t.column "job_code",               :string,    :limit => 20,                                :default => "",  :null => false
    t.column "description",            :string,                                                 :default => ""
    t.column "starting_date",          :date
    t.column "ending_date",            :date
    t.column "estimated_annual_fee",   :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "risk_id",                :integer
    t.column "status_id",              :integer
    t.column "partner_id",             :integer
    t.column "manager_id",             :integer
    t.column "referring_id",           :integer
    t.column "billing_partner_id",     :integer,                                                :default => 0,   :null => false
    t.column "billing_manager_id",     :integer,                                                :default => 0,   :null => false
    t.column "contracted_service_fee", :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "estimated_commision",    :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "estimated_outsorcing",   :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "budgeted_service_fee",   :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "service_PFA",            :integer,                                                :default => 0,   :null => false
    t.column "expense_PFA",            :integer,                                                :default => 0,   :null => false
    t.column "contracted_expense",     :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "budgeted_expense",       :decimal,                 :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "PFA_reason_id",          :integer
    t.column "revenue_id",             :integer,                                                :default => 0,   :null => false
  end

  add_index "projects", ["client_id", "GMU_id", "service_id", "risk_id", "status_id", "partner_id", "manager_id", "referring_id", "billing_partner_id", "billing_manager_id", "PFA_reason_id", "revenue_id"], :name => "prj_other_id"

  create_table "receive_amounts", :force => true do |t|
    t.column "created_on",     :datetime,                                                                 :null => false
    t.column "updated_on",     :datetime,                                                                 :null => false
    t.column "billing_id",     :integer,                                                :default => 0,    :null => false
    t.column "invoice_no",     :string,   :limit => 100,                                :default => "--", :null => false
    t.column "receive_date",   :string,   :limit => 30,                                 :default => ""
    t.column "receive_amount", :decimal,                 :precision => 10, :scale => 2, :default => 0.0,  :null => false
    t.column "job_code",       :string,   :limit => 20
  end

  create_table "sumselects", :force => true do |t|
    t.column "type",       :string,  :default => "", :null => false
    t.column "count_item", :integer, :default => 0,  :null => false
  end

  create_table "toupiao", :force => true do |t|
    t.column "name",   :string, :limit => 50,  :default => "", :null => false
    t.column "email",  :string, :limit => 100, :default => "", :null => false
    t.column "other",  :string,                :default => "", :null => false
    t.column "picked", :string, :limit => 1,   :default => "", :null => false
    t.column "other2", :string,                :default => "", :null => false
    t.column "other3", :string,                :default => "", :null => false
    t.column "other4", :string,                :default => "", :null => false
  end

  create_table "ufafees", :force => true do |t|
    t.column "created_on",  :timestamp,                                                 :null => false
    t.column "updated_on",  :timestamp,                                                 :null => false
    t.column "number",      :string
    t.column "amount",      :decimal,   :precision => 10, :scale => 2, :default => 0.0, :null => false
    t.column "project_id",  :integer
    t.column "period_id",   :integer
    t.column "service_UFA", :decimal,   :precision => 10, :scale => 2, :default => 0.0
    t.column "expense_UFA", :decimal,   :precision => 10, :scale => 2, :default => 0.0
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string,  :limit => 50, :default => "", :null => false
    t.column "person_id",       :integer, :limit => 8,  :default => 0,  :null => false
    t.column "hashed_password", :string,  :limit => 50, :default => "", :null => false
    t.column "auth",            :string,  :limit => 1, :default => "", :null => false
    t.column "other1",          :string,                :default => "", :null => false
    t.column "other2",          :string,                :default => "", :null => false
  end

  create_table "votes", :force => true do |t|
    t.column "username", :string,                :default => "", :null => false
    t.column "email",    :string,                :default => "", :null => false
    t.column "picked",   :string,  :limit => 10, :default => "", :null => false
    t.column "item_id",  :integer,               :default => 0,  :null => false
  end

end

